---
title: "Individual Assignment 5"
author: "Alyssa Hagele"
format: pdf
---

# 1. Set Up 


## Packages
```{r}
#| label: packages
#| message: false
#| warning: false

#general use and cleaning
library(tidyverse)
library(janitor) 
library(here)

# reading in .xlsx files
library(readxl)

```



## Data
```{r}
#| label: data
#| message: false
#| warning: false

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+")) 
```



## Class code 
```{r}
#| label: class code
#| message: false
#| warning: false



```











