---
title: "In-class tempelate Week 5"
author: "Alyssa Hagele" 
format: pdf
---

# Set Up 

## Packages 
```{r}
#| label: packages 
#| message: false
#| warning: false 

#general use and cleaning 
library(tidyverse)
library(here)
library(janitor) 
library(snakecase)

#wrap axis labels 
library(scales)

#reading .xlsx files
library(readxl)

#visualize missing data 
library(naniar)

#arrange plots 
library(patchwork)
```


## Data 
```{r}
#| label: data 
#| message: false
#| warning: false 

#taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

#aquatic invertebrates
aq_in <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Aquatic Insects")

#site information 
sites <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")


# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+"))
```

# 2. Cleaning 

## 'sites' object

Goal: create a new object from 'sites' that only includes NCOS sites

```{r}
#| label: ncos-sites 
#| message: false
#| warning: false 

# creating new object from sites
ncos_sites <- sites |> 
  # filter to only include NCOS sites sampled four times a year
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")
```







